---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dd-cyberia-mmo-client-development-blue
  namespace: default
  labels:
    app: dd-cyberia-mmo-client-development-blue
    deploy-id: dd-cyberia-mmo-client-development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dd-cyberia-mmo-client-development-blue
  template:
    metadata:
      labels:
        app: dd-cyberia-mmo-client-development-blue
        deploy-id: dd-cyberia-mmo-client-development
    spec:
      containers:
        - name: dd-cyberia-mmo-client-development-blue
          image: underpost/cyberia-client:v3.2.30
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: underpost-config
          ports:
            - containerPort: 8082

          command:
            - /bin/sh
            - -c
            - >
              set -a && . /home/dd/engine/engine-private/conf/dd-cyberia/instances/mmo-client/env/development.env && set +a && exec python3 /home/dd/engine/cyberia-client/docker-driver.py 8082 /home/dd/engine/cyberia-client/bin
          readinessProbe:
            {
              "tcpSocket": {
                "port": 8082
              },
              "initialDelaySeconds": 2,
              "periodSeconds": 5,
              "timeoutSeconds": 3,
              "failureThreshold": 6
            }
          livenessProbe:
            {
              "tcpSocket": {
                "port": 8082
              },
              "initialDelaySeconds": 30,
              "periodSeconds": 20,
              "timeoutSeconds": 5,
              "failureThreshold": 3
            }
          lifecycle:
            {
              "postStart": {
                "exec": {
                  "command": [
                    "sh",
                    "-c",
                    "underpost config set container-status dd-cyberia-mmo-client-development-initializing-deployment || true"
                  ]
                }
              },
              "preStop": {
                "exec": {
                  "command": [
                    "sh",
                    "-c",
                    "underpost config set container-status dd-cyberia-mmo-client-development-stopping-deployment || true"
                  ]
                }
              }
            }


    
          volumeMounts:
            - name: instance-cyberia-client-dd-cyberia-mmo-client-development-blue
              mountPath: /home/dd/engine/engine-private/conf/dd-cyberia/instances/mmo-client/env
    
      volumes:
        - name: instance-cyberia-client-dd-cyberia-mmo-client-development-blue
          persistentVolumeClaim:
            claimName: instance-cyberia-client-dd-cyberia-mmo-client-development-blue
    
      
---
apiVersion: v1
kind: Service
metadata:
  name: dd-cyberia-mmo-client-development-blue-service
  namespace: default
spec:
  selector:
    app: dd-cyberia-mmo-client-development-blue
  ports:
    - name: 'tcp-8082'
      protocol: TCP
      port: 8082
      targetPort: 8082
    - name: 'udp-8082'
      protocol: UDP
      port: 8082
      targetPort: 8082
  type: LoadBalancer